# backend/app/models.py
"""
Data Models - Auto-generated by GenCode Studio
"""
from typing import Optional, List
from datetime import datetime
from pydantic import BaseModel, Field, EmailStr
from beanie import Document, PydanticObjectId


class Assignee(BaseModel):
    """Embedded assignee details, used within Task documents. (EMBEDDED - Pydantic BaseModel)"""
    id: str = Field(..., description="Unique identifier for the assignee")
    name: str = Field(..., description="Name of the assignee")
    avatar: Optional[str] = Field(None, description="URL to assignee's avatar image")


class AssigneeCreate(BaseModel):
    """Create Assignee request"""
    name: str
    avatar: Optional[str] = None


class AssigneeResponse(BaseModel):
    """Response for Assignee"""
    id: str  # Beanie uses string IDs
    id: str
    name: str
    avatar: Optional[str] = None
    
    class Config:
        from_attributes = True


class Tag(BaseModel):
    """Embedded tag details, used within Task documents. (EMBEDDED - Pydantic BaseModel)"""
    id: str = Field(..., description="Unique identifier for the tag")
    name: str = Field(..., description="Name of the tag")
    color: Optional[str] = Field(None, description="Color associated with the tag")


class TagCreate(BaseModel):
    """Create Tag request"""
    name: str
    color: Optional[str] = None


class TagResponse(BaseModel):
    """Response for Tag"""
    id: str  # Beanie uses string IDs
    id: str
    name: str
    color: Optional[str] = None
    
    class Config:
        from_attributes = True


class Subtasks(Document):
    """Subtask completion status, embedded within Task documents. (AGGREGATE - Beanie Document)"""
    completed: int = Field(..., description="Number of completed subtasks")
    total: int = Field(..., description="Total number of subtasks")
    
    class Settings:
        name = "None"


class SubtasksCreate(BaseModel):
    """Create Subtasks request"""
    completed: int
    total: int


class SubtasksResponse(BaseModel):
    """Response for Subtasks"""
    id: str  # Beanie uses string IDs
    completed: int
    total: int
    
    class Config:
        from_attributes = True


class Task(Document):
    """Main task entity, stored as a top-level document. (AGGREGATE - Beanie Document)"""
    title: str = Field(..., description="Title of the task")
    description: str = Field(..., description="Detailed description of the task")
    status: str = Field(..., description="Current status of the task (backlog, in-progress, review, done)")
    priority: str = Field(..., description="Priority level of the task (low, medium, high)")
    assignee: Assignee = Field(..., description="Assigned user details (embedded Assignee object)")
    dueDate: str = Field(..., description="Due date of the task (ISO date string)")
    labels: List[Tag] = Field(..., description="List of tags associated with the task (embedded Tag objects)")
    subtasks: Subtasks = Field(..., description="Subtask completion details (embedded Subtasks object)")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when the task was created")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when the task was last updated")
    
    class Settings:
        name = "tasks"


class TaskCreate(BaseModel):
    """Create Task request"""
    title: str
    description: str
    status: str
    priority: str
    assignee: Assignee
    dueDate: str
    labels: List[Tag]
    subtasks: Subtasks


class TaskResponse(BaseModel):
    """Response for Task"""
    id: str  # Beanie uses string IDs
    title: str
    description: str
    status: str
    priority: str
    assignee: Assignee
    dueDate: str
    labels: List[Tag]
    subtasks: Subtasks
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True
