# app/workflow/engine_v2/fallback_api_agent.py
"""
Minimal JS API Client Generator (Used When Derek Fails)

Generates a minimal JS client with required exported functions.
Ensures frontend always has a valid API layer.
"""


class FallbackAPIAgent:
    """
    Generates a minimal JS client with required exported functions.
    Ensures frontend always has a valid API layer.
    """
    
    TEMPLATE = '''// frontend/src/lib/api.js
/**
 * API Client - Fallback Template
 * Generated by FallbackAPIAgent when LLM failed.
 */

const BASE = import.meta.env.VITE_API_URL || "http://localhost:8001/api";

/**
 * Generic fetch wrapper with error handling
 */
async function api(path, options = {}) {
  const url = `${BASE}${path}`;
  const response = await fetch(url, {
    headers: { "Content-Type": "application/json" },
    ...options,
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(error || response.statusText);
  }

  return response.json();
}

/**
 * Get all notes
 */
export async function getNotes(skip = 0, limit = 10) {
  return api(`/notes?skip=${skip}&limit=${limit}`);
}

/**
 * Get a single note by ID
 */
export async function getNoteById(id) {
  return api(`/notes/${id}`);
}

/**
 * Create a new note
 */
export async function createNote(payload) {
  return api("/notes", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * Update an existing note
 */
export async function updateNote(id, payload) {
  return api(`/notes/${id}`, {
    method: "PUT",
    body: JSON.stringify(payload),
  });
}

/**
 * Delete a note
 */
export async function deleteNote(id) {
  return api(`/notes/${id}`, {
    method: "DELETE",
  });
}

// Generic exports for flexibility
export { api };
export const get = (path) => api(path);
export const post = (path, data) => api(path, { method: "POST", body: JSON.stringify(data) });
export const put = (path, data) => api(path, { method: "PUT", body: JSON.stringify(data) });
export const del = (path) => api(path, { method: "DELETE" });
'''

    def __init__(self, entity: str = "note"):
        """
        Args:
            entity: The entity name (e.g., "note", "task", "user")
        """
        self.entity = entity

    def generate(self) -> str:
        """Generate the fallback API client code."""
        return self.TEMPLATE.strip()

    def generate_for_entity(self, entity: str, entity_plural: str = None) -> str:
        """Generate an API client for a specific entity."""
        entity_lower = entity.lower()
        entity_cap = entity.capitalize()
        # Allow explicit plural or auto-generate
        if entity_plural is None:
            entity_plural = entity_lower + "s" if not entity_lower.endswith("s") else entity_lower
        
        return f'''// frontend/src/lib/api.js
/**
 * API Client for {entity_cap} - Fallback Template
 */

const BASE = import.meta.env.VITE_API_URL || "http://localhost:8001/api";

async function api(path, options = {{}}) {{
  const url = `${{BASE}}${{path}}`;
  const response = await fetch(url, {{
    headers: {{ "Content-Type": "application/json" }},
    ...options,
  }});

  if (!response.ok) {{
    const error = await response.text();
    throw new Error(error || response.statusText);
  }}

  return response.json();
}}

export async function get{entity_cap}s(skip = 0, limit = 10) {{
  return api(`/{entity_plural}?skip=${{skip}}&limit=${{limit}}`);
}}

export async function get{entity_cap}ById(id) {{
  return api(`/{entity_plural}/${{id}}`);
}}

export async function create{entity_cap}(payload) {{
  return api("/{entity_plural}", {{
    method: "POST",
    body: JSON.stringify(payload),
  }});
}}

export async function update{entity_cap}(id, payload) {{
  return api(`/{entity_plural}/${{id}}`, {{
    method: "PUT",
    body: JSON.stringify(payload),
  }});
}}

export async function delete{entity_cap}(id) {{
  return api(`/{entity_plural}/${{id}}`, {{
    method: "DELETE",
  }});
}}

export {{ api }};
export const get = (path) => api(path);
export const post = (path, data) => api(path, {{ method: "POST", body: JSON.stringify(data) }});
export const put = (path, data) => api(path, {{ method: "PUT", body: JSON.stringify(data) }});
export const del = (path) => api(path, {{ method: "DELETE" }});
'''.strip()
