# backend/app/main.py
"""
FastAPI Main Application - Auto-generated by Self-Healing Manager (DYNAMIC)
"""
from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.database import init_db
# @ROUTER_IMPORTS - DO NOT REMOVE THIS LINE


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialize database on startup."""
    await init_db()
    yield


app = FastAPI(
    title="Notes API",
    description="A note management API",
    version="1.0.0",
    lifespan=lifespan,
)

# CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# @ROUTER_REGISTER - DO NOT REMOVE THIS LINE


@app.get("/api/health")
async def health_check():
    """Health check endpoint."""
    return {"status": "healthy"}
