# backend/app/routers/notes.py
"""
Note CRUD Router - Fallback Template
Generated by FallbackRouterAgent when LLM failed.
"""
from fastapi import APIRouter, HTTPException, Query
from typing import List
from beanie import PydanticObjectId

from app.models import Note

# NOTE: No prefix here - main.py adds prefix when including router
router = APIRouter()


@router.post("/", response_model=Note, status_code=201)
async def create(note: Note):
    """Create a new note."""
    await note.create()
    return note


@router.get("/", response_model=List[Note])
async def get_all(
    skip: int = Query(0, ge=0),
    limit: int = Query(10, ge=1, le=100),
):
    """Get all notes with pagination."""
    return await Note.find_all().skip(skip).limit(limit).to_list()


@router.get("/{note_id}", response_model=Note)
async def get_one(note_id: PydanticObjectId):
    """Get a single note by ID."""
    note = await Note.get(note_id)
    if not note:
        raise HTTPException(status_code=404, detail="Note not found")
    return note


@router.put("/{note_id}", response_model=Note)
async def update(note_id: PydanticObjectId, data: dict):
    """Update an existing note."""
    note = await Note.get(note_id)
    if not note:
        raise HTTPException(status_code=404, detail="Note not found")
    await note.set(data)
    return note


@router.delete("/{note_id}")
async def delete(note_id: PydanticObjectId):
    """Delete a note."""
    note = await Note.get(note_id)
    if not note:
        raise HTTPException(status_code=404, detail="Note not found")
    await note.delete()
    return {"status": "deleted", "id": str(note_id)}