# backend/app/models.py
"""
Task Model - Fallback Template
Generated by FallbackModelAgent when LLM failed.
"""
from datetime import datetime, timezone
from typing import Optional
from beanie import Document
from pydantic import Field


class Task(Document):
    """Main entity model for task."""
    title: str = Field(..., description="Title of the task")
    content: str = Field(default="", description="Content/description")
    status: str = Field(default="Draft", description="Status: Draft, Active, Completed")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: Optional[datetime] = None
    
    class Settings:
        name = "tasks"
        
    class Config:
        json_schema_extra = {
            "example": {
                "title": "Sample Task",
                "content": "Example content",
                "status": "Draft"
            }
        }
