# backend/app/models.py
"""
Data Models - Auto-generated by GenCode Studio
"""
from typing import Optional, List
from datetime import datetime
from pydantic import BaseModel, Field, EmailStr
from beanie import Document, PydanticObjectId


class EmbeddedAssignee(Document):
    """Embedded Assignee object for Task (AGGREGATE - Beanie Document)"""
    id: Optional[Optional[str]] = Field(None, description="Unique identifier for the assignee")
    name: str = Field(..., description="Name of the assignee")
    avatar: str = Field(..., description="URL to the assignee's avatar image")
    
    class Settings:
        name = "None"


class EmbeddedAssigneeCreate(BaseModel):
    """Create EmbeddedAssignee request"""
    name: str
    avatar: str


class EmbeddedAssigneeResponse(BaseModel):
    """Response for EmbeddedAssignee"""
    id: str  # Beanie uses string IDs
    id: Optional[Optional[str]] = None
    name: str
    avatar: str
    
    class Config:
        from_attributes = True


class EmbeddedTag(Document):
    """Embedded Tag object for Task (AGGREGATE - Beanie Document)"""
    id: Optional[Optional[str]] = Field(None, description="Unique identifier for the tag")
    name: str = Field(..., description="Name of the tag")
    color: str = Field(..., description="Color code or class for the tag (e.g., 'bg-blue-500')")
    
    class Settings:
        name = "None"


class EmbeddedTagCreate(BaseModel):
    """Create EmbeddedTag request"""
    name: str
    color: str


class EmbeddedTagResponse(BaseModel):
    """Response for EmbeddedTag"""
    id: str  # Beanie uses string IDs
    id: Optional[Optional[str]] = None
    name: str
    color: str
    
    class Config:
        from_attributes = True


class Subtask(Document):
    """Embedded Subtask object for Task (AGGREGATE - Beanie Document)"""
    completed: int = Field(..., description="Number of completed subtasks")
    total: int = Field(..., description="Total number of subtasks")
    
    class Settings:
        name = "None"


class SubtaskCreate(BaseModel):
    """Create Subtask request"""
    completed: int
    total: int


class SubtaskResponse(BaseModel):
    """Response for Subtask"""
    id: str  # Beanie uses string IDs
    completed: int
    total: int
    
    class Config:
        from_attributes = True


class Assignee(Document):
    """Top-level Assignee entity (AGGREGATE - Beanie Document)"""
    name: str = Field(..., description="Name of the assignee")
    avatar: str = Field(..., description="URL to the assignee's avatar image")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="Last update timestamp")
    
    class Settings:
        name = "assignees"


class AssigneeCreate(BaseModel):
    """Create Assignee request"""
    name: str
    avatar: str


class AssigneeResponse(BaseModel):
    """Response for Assignee"""
    id: str  # Beanie uses string IDs
    name: str
    avatar: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True


class Tag(Document):
    """Top-level Tag entity (AGGREGATE - Beanie Document)"""
    name: str = Field(..., description="Name of the tag")
    color: str = Field(..., description="Color code or class for the tag (e.g., 'bg-blue-500')")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="Last update timestamp")
    
    class Settings:
        name = "tags"


class TagCreate(BaseModel):
    """Create Tag request"""
    name: str
    color: str


class TagResponse(BaseModel):
    """Response for Tag"""
    id: str  # Beanie uses string IDs
    name: str
    color: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True


class Task(Document):
    """Top-level Task entity (AGGREGATE - Beanie Document)"""
    title: str = Field(..., description="Title of the task")
    description: str = Field(..., description="Detailed description of the task")
    status: str = Field(..., description="Current status of the task (e.g., 'Backlog', 'In Progress', 'Review', 'Done')")
    priority: str = Field(..., description="Priority level of the task (e.g., 'Low', 'Medium', 'High')")
    assignee: EmbeddedAssignee = Field(..., description="Embedded assignee details for the task")
    dueDate: str = Field(..., description="Due date of the task in YYYY-MM-DD format")
    tags: List[EmbeddedTag] = Field(..., description="List of embedded tags associated with the task")
    subtasks: Subtask = Field(..., description="Embedded subtask progress details")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="Last update timestamp")
    
    class Settings:
        name = "tasks"


class TaskCreate(BaseModel):
    """Create Task request"""
    title: str
    description: str
    status: str
    priority: str
    assignee: EmbeddedAssignee
    dueDate: str
    tags: List[EmbeddedTag]
    subtasks: Subtask


class TaskResponse(BaseModel):
    """Response for Task"""
    id: str  # Beanie uses string IDs
    title: str
    description: str
    status: str
    priority: str
    assignee: EmbeddedAssignee
    dueDate: str
    tags: List[EmbeddedTag]
    subtasks: Subtask
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True
