# app/orchestration/fallback_model_agent.py
"""
Fallback Model Generator - Single source of truth for model fallback generation.

Used when Derek fails to generate a valid Beanie model.
Consolidates model generation from:
- self_healing_manager._get_model_template()
- healing_pipeline._generate_fallback_model()

IMPORTANT: This agent is ALWAYS DYNAMIC.
- Entity and model_name are REQUIRED parameters
- No hardcoded defaults
"""
from app.utils.entity_discovery import get_entity_plural


class FallbackModelAgent:
    """
    Generates minimal but valid Beanie Document model templates.
    Used ONLY when main LLM agent repeatedly fails.
    
    DYNAMIC: Always requires entity parameter - no hardcoded defaults.
    """
    
    def __init__(self):
        """Initialize the fallback model agent."""
        pass

    def generate(self, entity: str, model_name: str) -> str:
        """
        Generate model code for the specified entity.
        
        Args:
            entity: Entity name (e.g., "product", "task", "note")
            model_name: Model class name (e.g., "Product", "Task", "Note")
        
        Returns:
            Complete Beanie Document model code as a string
            
        Raises:
            ValueError: If entity or model_name not provided
        """
        if not entity or not model_name:
            raise ValueError(
                "FallbackModelAgent.generate() requires entity and model_name! "
                "Use entity_discovery.discover_primary_entity() to get them."
            )
        return self.generate_for_entity(entity, model_name)

    def generate_for_entity(self, entity: str, model_name: str) -> str:
        """
        Generate a Beanie Document model for a specific entity.
        
        Args:
            entity: Base entity name (e.g., "product", "task", "note")
            model_name: Model class name (e.g., "Product", "Task", "Note")
            
        Returns:
            Complete Beanie Document model code with Settings and Config
        """
        if not entity or not model_name:
            raise ValueError("entity and model_name are required!")
        
        entity_lower = entity.lower()
        entity_plural = get_entity_plural(entity_lower)
        
        return f'''# backend/app/models.py
"""
{model_name} Model - Fallback Template
Generated by FallbackModelAgent when LLM failed.
"""
from datetime import datetime, timezone
from typing import Optional
from beanie import Document
from pydantic import Field


class {model_name}(Document):
    """Main entity model for {entity_lower}."""
    title: str = Field(..., description="Title of the {entity_lower}")
    content: str = Field(default="", description="Content/description")
    status: str = Field(default="Draft", description="Status: Draft, Active, Completed")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: Optional[datetime] = None
    
    class Settings:
        name = "{entity_plural}"
        
    class Config:
        json_schema_extra = {{
            "example": {{
                "title": "Sample {model_name}",
                "content": "Example content",
                "status": "Draft"
            }}
        }}
'''
