# app/orchestration/fallback_api_agent.py
"""
Minimal JS API Client Generator (Used When Derek Fails)

Generates a minimal JS client with required exported functions.
Ensures frontend always has a valid API layer.

IMPORTANT: This agent is ALWAYS DYNAMIC.
- Entity is a REQUIRED parameter
- No hardcoded defaults like "note" or "item"
- Uses centralized entity_discovery for pluralization
"""
from app.utils.entity_discovery import get_entity_plural


class FallbackAPIAgent:
    """
    Generates a minimal JS client with required exported functions.
    Ensures frontend always has a valid API layer.
    
    DYNAMIC: Always requires entity parameter - no hardcoded defaults.
    """
    
    # NOTE: Removed hardcoded TEMPLATE constant that used "notes/Note".
    # All generation now uses generate_for_entity() which is fully dynamic.
    
    def __init__(self):
        """
        Initialize the fallback API agent.
        
        NOTE: Removed entity parameter with default "note".
        Entity is now always passed to generate() or generate_for_entity().
        """
        pass

    def generate(self, entity: str, entity_plural: str = None) -> str:
        """
        Generate API client code for the specified entity.
        
        Args:
            entity: Entity name (e.g., "product", "task", "user")
            entity_plural: Optional plural form (auto-generated if not provided)
        
        Returns:
            Complete JS API client code as a string
            
        Raises:
            ValueError: If entity not provided
        
        BREAKING CHANGE: Entity is now REQUIRED.
        No more hardcoded defaults like "Note" or "Item".
        """
        if not entity:
            raise ValueError(
                "FallbackAPIAgent.generate() requires entity! "
                "Use entity_discovery.discover_primary_entity() to get it. "
                "No hardcoded defaults are allowed."
            )
        return self.generate_for_entity(entity, entity_plural)

    def generate_for_entity(self, entity: str, entity_plural: str = None) -> str:
        """
        Generate an API client for a specific entity.
        
        Args:
            entity: Base entity name (e.g., "product", "task")
            entity_plural: Optional plural form (e.g., "products", "tasks")
            
        Returns:
            Complete JavaScript API client with all CRUD functions
        """
        if not entity:
            raise ValueError("entity is required!")
        
        entity_lower = entity.lower()
        entity_cap = entity.capitalize()
        
        # Use centralized pluralization if not provided
        if entity_plural is None:
            entity_plural = get_entity_plural(entity_lower)
        
        return f'''// frontend/src/lib/api.js
/**
 * API Client for {entity_cap} - Fallback Template
 * Generated by FallbackAPIAgent when LLM failed.
 */

const BASE = import.meta.env.VITE_API_URL || "http://localhost:8001";

/**
 * Generic fetch wrapper with error handling
 * Automatically adds /api prefix to paths that don't have it
 */
async function api(path, options = {{}}) {{
  // Smartly handle paths (prevent /api/api/...)
  const endpoint = path.startsWith("/api") ? path : `/api${{path}}`;
  const url = `${{BASE}}${{endpoint}}`;
  const response = await fetch(url, {{
    headers: {{ "Content-Type": "application/json" }},
    ...options,
  }});

  if (!response.ok) {{
    const error = await response.text();
    throw new Error(error || response.statusText);
  }}

  return response.json();
}}

/**
 * Get all {entity_plural}
 */
export async function get{entity_cap}s(skip = 0, limit = 10) {{
  return api(`/{entity_plural}?skip=${{skip}}&limit=${{limit}}`);
}}

/**
 * Get a single {entity_lower} by ID
 */
export async function get{entity_cap}ById(id) {{
  return api(`/{entity_plural}/${{id}}`);
}}

/**
 * Create a new {entity_lower}
 */
export async function create{entity_cap}(payload) {{
  return api("/{entity_plural}", {{
    method: "POST",
    body: JSON.stringify(payload),
  }});
}}

/**
 * Update an existing {entity_lower}
 */
export async function update{entity_cap}(id, payload) {{
  return api(`/{entity_plural}/${{id}}`, {{
    method: "PUT",
    body: JSON.stringify(payload),
  }});
}}

/**
 * Delete a {entity_lower}
 */
export async function delete{entity_cap}(id) {{
  return api(`/{entity_plural}/${{id}}`, {{
    method: "DELETE",
  }});
}}

// Generic exports for flexibility
export {{ api }};
export const get = (path) => api(path);
export const post = (path, data) => api(path, {{ method: "POST", body: JSON.stringify(data) }});
export const put = (path, data) => api(path, {{ method: "PUT", body: JSON.stringify(data) }});
export const del = (path) => api(path, {{ method: "DELETE" }});
'''.strip()
