# backend/app/routers/tasks.py
"""
Task CRUD Router - Fallback Template
Generated by FallbackRouterAgent when LLM failed.
"""
from fastapi import APIRouter, HTTPException, Query
from typing import List
from beanie import PydanticObjectId

from app.models import Task

# NOTE: No prefix here - main.py adds prefix when including router
router = APIRouter()


@router.post("/", response_model=Task, status_code=201)
async def create(task: Task):
    """Create a new task."""
    await task.create()
    return task


@router.get("/", response_model=List[Task])
async def get_all(
    skip: int = Query(0, ge=0),
    limit: int = Query(10, ge=1, le=100),
):
    """Get all tasks with pagination."""
    return await Task.find_all().skip(skip).limit(limit).to_list()


@router.get("/{task_id}", response_model=Task)
async def get_one(task_id: PydanticObjectId):
    """Get a single task by ID."""
    task = await Task.get(task_id)
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    return task


@router.put("/{task_id}", response_model=Task)
async def update(task_id: PydanticObjectId, data: dict):
    """Update an existing task."""
    task = await Task.get(task_id)
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    await task.set(data)
    return task


@router.delete("/{task_id}")
async def delete(task_id: PydanticObjectId):
    """Delete a task."""
    task = await Task.get(task_id)
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    await task.delete()
    return {"status": "deleted", "id": str(task_id)}