# backend/app/models.py
"""
Data Models - Auto-generated by GenCode Studio
"""
from typing import Optional, List
from datetime import datetime
from pydantic import BaseModel, Field, EmailStr
from beanie import Document, PydanticObjectId

# Phase 0: Failure Boundary Enforcement
from app.core.failure_boundary import FailureBoundary


class Lead(Document):
    """Represents a potential customer or prospect. (AGGREGATE - Beanie Document)"""
    name: str = Field(..., description="Full name of the lead")
    company: str = Field(..., description="Company of the lead")
    email: str = Field(..., description="Email address of the lead")
    phone: str = Field(..., description="Phone number of the lead")
    status: str = Field(..., description="Current status of the lead (e.g., New, Contacted, Qualified, Won, Lost)")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when the lead was created")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when the lead was last updated")
    last_contacted: Optional[Optional[datetime]] = Field(None, description="Timestamp of the last contact with the lead")
    
    class Settings:
        name = "leads"


class LeadCreate(BaseModel):
    """Create Lead request"""
    name: str
    company: str
    email: str
    phone: str
    status: str
    last_contacted: Optional[Optional[datetime]] = None


class LeadResponse(BaseModel):
    """Response for Lead"""
    id: str  # Beanie uses string IDs
    name: str
    company: str
    email: str
    phone: str
    status: str
    created_at: datetime
    updated_at: datetime
    last_contacted: Optional[Optional[datetime]] = None
    
    class Config:
        from_attributes = True


class Note(Document):
    """A note associated with a specific lead. (AGGREGATE - Beanie Document)"""
    lead_id: PydanticObjectId = Field(..., description="Reference to the Lead this note belongs to")
    content: str = Field(..., description="The content of the note")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when the note was created")
    updated_at: datetime = Field(default_factory=datetime.utcnow, description="Timestamp when the note was last updated")
    
    class Settings:
        name = "notes"


class NoteCreate(BaseModel):
    """Create Note request"""
    lead_id: PydanticObjectId
    content: str


class NoteResponse(BaseModel):
    """Response for Note"""
    id: str  # Beanie uses string IDs
    lead_id: PydanticObjectId
    content: str
    created_at: datetime
    updated_at: datetime
    
    class Config:
        from_attributes = True
