// frontend/src/lib/api.js
/**
 * API Client for Assignee - Fallback Template
 * Generated by FallbackAPIAgent when LLM failed.
 */

const BASE = import.meta.env.VITE_API_URL || "http://localhost:8001";

/**
 * Generic fetch wrapper with error handling
 * Automatically adds /api prefix to paths that don't have it
 */
async function api(path, options = {}) {
  // Smartly handle paths (prevent /api/api/...)
  const endpoint = path.startsWith("/api") ? path : `/api${path}`;
  const url = `${BASE}${endpoint}`;
  const response = await fetch(url, {
    headers: { "Content-Type": "application/json" },
    ...options,
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(error || response.statusText);
  }

  return response.json();
}

/**
 * Get all assignees
 */
export async function getAssignees(skip = 0, limit = 10) {
  return api(`/assignees?skip=${skip}&limit=${limit}`);
}

/**
 * Get a single assignee by ID
 */
export async function getAssigneeById(id) {
  return api(`/assignees/${id}`);
}

/**
 * Create a new assignee
 */
export async function createAssignee(payload) {
  return api("/assignees", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

/**
 * Update an existing assignee
 */
export async function updateAssignee(id, payload) {
  return api(`/assignees/${id}`, {
    method: "PUT",
    body: JSON.stringify(payload),
  });
}

/**
 * Delete a assignee
 */
export async function deleteAssignee(id) {
  return api(`/assignees/${id}`, {
    method: "DELETE",
  });
}

// Generic exports for flexibility
export { api };
export const get = (path) => api(path);
export const post = (path, data) => api(path, { method: "POST", body: JSON.stringify(data) });
export const put = (path, data) => api(path, { method: "PUT", body: JSON.stringify(data) });
export const del = (path) => api(path, { method: "DELETE" });