# app/core/constants.py
"""
Application constants - all magic numbers and strings in one place.
"""

# Workflow Steps - Emergent E1-style workflow (Frontend-First)
class WorkflowStep:
    """
    E1-style workflow steps (Frontend-First pattern from Emergent).
    
    Order (12 steps total):
    1. ANALYSIS - Understand and clarify requirements
    2. ARCHITECTURE - Design system architecture
    3. FRONTEND_MOCK - Create frontend with mock data (aha moment!)
    4. SCREENSHOT_VERIFY - Visual QA of the frontend
    5. CONTRACTS - Define API contracts based on frontend mock
    6. BACKEND_MODELS - Create database models
    7. BACKEND_ROUTERS - Create API endpoints
    8. BACKEND_MAIN - Wire up the main app
    9. TESTING_BACKEND - Test backend with pytest
    10. FRONTEND_INTEGRATION - Replace mock with real API calls
    11. TESTING_FRONTEND - E2E tests with Playwright
    12. PREVIEW_FINAL - Show the running application
    """
    # Step 1
    ANALYSIS = "analysis"
    # Step 2
    ARCHITECTURE = "architecture"
    # Step 3: Frontend-first with mock data (Emergent pattern)
    FRONTEND_MOCK = "frontend_mock"
    # Step 4: Visual QA
    SCREENSHOT_VERIFY = "screenshot_verify"
    # Step 5: API contracts derived from mock data
    CONTRACTS = "contracts"
    # Step 6
    BACKEND_MODELS = "backend_models"
    # Step 7
    BACKEND_ROUTERS = "backend_routers"
    # Step 8
    BACKEND_MAIN = "backend_main"
    # Step 9
    TESTING_BACKEND = "testing_backend"
    # Step 10: Replace mock with API calls
    FRONTEND_INTEGRATION = "frontend_integration"
    # Step 11
    TESTING_FRONTEND = "testing_frontend"
    # Step 12
    PREVIEW_FINAL = "preview_final"
    # Post-workflow refinement (user sends follow-up messages)
    REFINE = "refine"
    # Workflow completion marker
    COMPLETE = "complete"


# LLM Configuration
# PHASE 5 OPTIMIZATION: Reduced to force conciseness (5-10% token savings)
# Previous: 16000, New: 10000 (agents must be more concise)
DEFAULT_MAX_TOKENS = 10000
# Previous: 20000, New: 12000 (test files still get more tokens but optimized)
TEST_FILE_MIN_TOKENS = 12000

# Agent Names
class AgentName:
    """Agent identifiers."""
    MARCUS = "Marcus"
    DEREK = "Derek"
    LUNA = "Luna"
    VICTORIA = "Victoria"


# ═══════════════════════════════════════════════════════
# PROTECTED FILES - Infrastructure files agents cannot modify
# ═══════════════════════════════════════════════════════
#
# These are critical Docker/deployment infrastructure files that:
# 1. Control how containers are built and orchestrated
# 2. Are NOT generated by agents - they come from templates
# 3. If modified incorrectly, would break the entire sandbox
#
# WHY NO BACKEND FILES?
# - backend/Dockerfile: Derek may need to fix Python deps or versions
# - backend/app/*.py: All agent-generated code, Derek must be able to fix
# - backend/requirements.txt: Derek may need to add missing packages
#
# WHY FRONTEND DOCKERFILE IS PROTECTED?
# - Frontend uses a template Dockerfile with Vite/Node setup
# - Agents don't understand Node build processes well
# - Breaking this would prevent frontend from building
#
PROTECTED_FILES = {
    "frontend/Dockerfile",
    "docker-compose.yml",
    ".dockerignore",
}

# Alias for backwards compatibility - both refer to the same set
PROTECTED_SANDBOX_FILES = PROTECTED_FILES

# ═══════════════════════════════════════════════════════
# FILE WRITE POLICY - Simple "protected files only" approach
# ═══════════════════════════════════════════════════════
# 
# Agents can write to ANY file EXCEPT those in PROTECTED_FILES.
# This is simpler and more flexible than maintaining allowlists.

# WebSocket Message Types
class WSMessageType:
    """WebSocket message types."""
    WORKFLOW_UPDATE = "WORKFLOW_UPDATE"
    WORKFLOW_COMPLETE = "WORKFLOW_COMPLETE"
    WORKFLOW_FAILED = "WORKFLOW_FAILED"
    WORKFLOW_PAUSED = "WORKFLOW_PAUSED"
    AGENT_LOG = "AGENT_LOG"
    PREVIEW_URL_READY = "PREVIEW_URL_READY"
    QUALITY_GATE_BLOCKED = "QUALITY_GATE_BLOCKED"
    WORKSPACE_UPDATED = "WORKSPACE_UPDATED"
    WORKFLOW_RESUMED = "WORKFLOW_RESUMED"
    AGENT_MESSAGE = "AGENT_MESSAGE"


# Default file content templates
DEFAULT_REQUIREMENTS = """fastapi>=0.115.0
uvicorn[standard]>=0.32.0
pydantic>=2.9.0
motor>=3.6.0
beanie>=1.26.0
python-dotenv>=1.0.0
httpx>=0.27.0
pytest>=8.0.0
pytest-asyncio>=0.24.0
aiohttp>=3.11.0
"""

# Updated DEFAULT_PACKAGE_JSON with all shadcn/ui dependencies (matches package.example.json)
# NOTE: Using TailwindCSS v4.x to match Frontend/package.json
DEFAULT_PACKAGE_JSON = """{
  "name": "frontend",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview",
    "test": "npx playwright test",
    "lint": "echo \\"no lint step configured\\""
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router-dom": "^6.20.0",
    "lucide-react": "^0.294.0",
    "clsx": "^2.0.0",
    "tailwind-merge": "^3.0.0",
    "class-variance-authority": "^0.7.0",
    "@radix-ui/react-accordion": "^1.2.0",
    "@radix-ui/react-alert-dialog": "^1.1.0",
    "@radix-ui/react-aspect-ratio": "^1.1.0",
    "@radix-ui/react-avatar": "^1.1.0",
    "@radix-ui/react-checkbox": "^1.1.0",
    "@radix-ui/react-collapsible": "^1.1.0",
    "@radix-ui/react-context-menu": "^2.2.0",
    "@radix-ui/react-dialog": "^1.1.0",
    "@radix-ui/react-dropdown-menu": "^2.1.0",
    "@radix-ui/react-hover-card": "^1.1.0",
    "@radix-ui/react-label": "^2.1.0",
    "@radix-ui/react-menubar": "^1.1.0",
    "@radix-ui/react-navigation-menu": "^1.2.0",
    "@radix-ui/react-popover": "^1.1.0",
    "@radix-ui/react-progress": "^1.1.0",
    "@radix-ui/react-radio-group": "^1.2.0",
    "@radix-ui/react-scroll-area": "^1.2.0",
    "@radix-ui/react-select": "^2.1.0",
    "@radix-ui/react-separator": "^1.1.0",
    "@radix-ui/react-slider": "^1.2.0",
    "@radix-ui/react-slot": "^1.1.0",
    "@radix-ui/react-switch": "^1.1.0",
    "@radix-ui/react-tabs": "^1.1.0",
    "@radix-ui/react-toggle": "^1.1.0",
    "@radix-ui/react-toggle-group": "^1.1.0",
    "@radix-ui/react-tooltip": "^1.1.0",
    "cmdk": "^1.0.0",
    "embla-carousel-react": "^8.0.0",
    "input-otp": "^1.2.0",
    "react-day-picker": "^9.0.0",
    "react-hook-form": "^7.50.0",
    "react-resizable-panels": "^2.0.0",
    "recharts": "^2.12.0",
    "sonner": "^1.4.0",
    "vaul": "^1.0.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^5.0.0",
    "@playwright/test": "1.57.0",
    "autoprefixer": "^10.4.21",
    "postcss": "^8.5.0",
    "tailwindcss": "^4.0.0",
    "tailwindcss-animate": "^1.0.7"
  }
}
"""

