# app/core/types.py
"""
Shared type definitions used across the application.
"""
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional, TypedDict, Union
from enum import Enum


# TypedDict for chat messages
class ChatMessage(TypedDict):
    role: str
    content: str





# File output from agents (dataclass version)
@dataclass
class GeneratedFile:
    """A file generated by an agent."""
    path: str
    content: str
    
    def to_dict(self) -> Dict[str, str]:
        return {"path": self.path, "content": self.content}



# Agent output structure
@dataclass
class AgentOutput:
    """Output from an agent call."""
    files: List[GeneratedFile] = field(default_factory=list)
    thinking: str = ""
    raw: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "files": [f.to_dict() for f in self.files],
            "thinking": self.thinking,
        }





# Workflow step result
@dataclass
class StepResult:
    """Result of executing a workflow step."""
    nextstep: str
    turn: int
    pause: bool = False
    status: str = "ok"
    data: Dict[str, Any] = field(default_factory=dict)


# Quality metrics
@dataclass
class QualityMetrics:
    """Quality metrics for a project."""
    total_files: int = 0
    total_lines: int = 0
    avg_quality_score: float = 0.0
    approvals: int = 0
    rejections: int = 0


# Token usage for cost tracking
@dataclass
class TokenUsage:
    """Track token usage for cost estimation."""
    input_tokens: int = 0
    output_tokens: int = 0
    
    @property
    def total(self) -> int:
        return self.input_tokens + self.output_tokens
    
    @property
    def estimated_cost(self) -> float:
        """Estimate cost based on Gemini pricing."""
        input_cost = (self.input_tokens / 1000) * 0.00025
        output_cost = (self.output_tokens / 1000) * 0.0005
        return round(input_cost + output_cost, 6)


# Workflow state
class WorkflowStatus(Enum):
    """Status of a workflow."""
    RUNNING = "running"
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"





# ============================================================
# TypedDict types (from legacy agents/types.py)
# ============================================================




class QAIssue(TypedDict):
    """Quality assurance issue from Derek/Luna."""
    file: str
    line: int
    area: str
    description: str
    severity: Literal['critical', 'major', 'minor']
    suggested_fix: str
    codeContext: Optional[str]
    testableImpact: Optional[str]


class FilePlan(TypedDict):
    """File plan for workflow."""
    path: str
    description: str


class TestReport(TypedDict):
    """Test report from QA agents."""
    summary: str
    passed: bool
    issueCount: Optional[int]
    severityBreakdown: Optional[Dict[str, int]]
    issues: List[QAIssue]
    recommendations: Optional[List[str]]


class ToolCall(TypedDict):
    """A tool call from Marcus."""
    name: str
    args: Dict[str, Any]


class MarcusPlan(TypedDict):
    """Marcus's planning output."""
    thought: str
    tool_call: Optional[ToolCall]
    speak_to_user: Optional[str]

